version: '3.9'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    container_name: node-container
    ports:
      - '4000:4000'
    volumes:
      - './server:/app'
      - '/app/node_modules'
  client:
    container_name: react-container
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    command: npm start
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - landing-network
networks:
  landing-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local